/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ForPanel;

import ForClass.DataConnection;
import ForUserControl.ucService;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author Tang Seakmeng
 */

public class List_Services1 extends javax.swing.JPanel {

    /**
     * Creates new form List_Services
     */
    
    public List_Services1() {
        initComponents();

        int x = 5, y = 5;
        int col = 5;
        int col_increment = 0;
        
        ucService uc;

//        try
//        {
//            String sql = "select name, image, price from tblService";
//            
//            Statement s = DataConnection.getDataCon().createStatement();
//            ResultSet r = s.executeQuery(sql);
//            
//            while(r.next())
//            {
//                uc = new ucService(r.getString(1) + "", r.getString(2) + "", r.getString(3) + "");
//                add(uc, new AbsoluteConstraints(x, y, 190, 260));
//                
//                if(col_increment >= col)
//                {
//                    x = 5;
//                    y += 260;
//                    
//                    col_increment = 0;
//                }
//                else if(col_increment < col)
//                {
//                    x += 180;
//                    
//                    col_increment++;
//                }
//            }
//            
//            r.close();
//        } 
//        catch (SQLException e) 
//        {
//            System.out.println(e.getMessage());
//        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
