/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ForPanel;

import ForClass.DataConnection;
import ForUserControl.ucTable;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author Tang Seakmeng
 */
public class List_Tables extends javax.swing.JPanel {

    /**
     * Creates new form List_Tables
     */
    public List_Tables() {
        initComponents();
        
        getTables();
    }
    
    ucTable uc;
    
    private void getTables()
    {
        int x = 5, y = 5;
        int col = 3;
        int col_increment = 0;
        String[] arr = new String[9];
        
        try
        {
            String sql = "select t.tablename, t.description, tc.tablecategoryname from tblTables t inner join tblTableCategory tc on t.tablecategoryid = tc.id";
            
            Statement s = DataConnection.getDataCon().createStatement();
            ResultSet r = s.executeQuery(sql);
            
            while(r.next())
            {
                arr[0] = r.getString(1);
                arr[2] = r.getString(2);
                arr[3] = r.getString(3);
                arr[4] = "Status";
                arr[5] = "Available";
                arr[6] = "0";
                arr[7] = "2";
                arr[8] = "235";
                
                uc = new ucTable(arr);
                //add(uc, new AbsoluteConstraints(x, y, 180, 260));
                jPanel1.add(uc, new AbsoluteConstraints(x, y, 392, 168));
                
                if(col_increment > col)
                {
                    x = 5;
                    y += 173;
                    
                    col_increment = 0;
                }
                else if(col_increment < col)
                {
                    x += 397;
                    
                    col_increment++;
                }
            }
            
            r.close();
        } 
        catch (SQLException e) 
        {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(1300, 690));
        setPreferredSize(new java.awt.Dimension(1207, 745));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setText("Date :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        add(jXDatePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setText("Time :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jSpinner1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 50, -1));

        jSpinner2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 50, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setText(":");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 10, -1));

        jButton2.setText("Search");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1280, 670));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    // End of variables declaration//GEN-END:variables
}
