/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ForPanel;

import ForClass.DataConnection;
import ForUserControl.ucService;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author Tang Seakmeng
 */

public class List_Services extends javax.swing.JPanel {

    /**
     * @return the order_table
     */
    public ForComponent.SubJTable getOrder_table() {
        return order_table;
    }

    /**
     * @param order_table the order_table to set
     */
    public void setOrder_table(ForComponent.SubJTable order_table) {
        this.order_table = order_table;
    }

    /**
     * Creates new form List_Services
     */
    
    public List_Services() {
        initComponents();  
        
        getUC("MainFood");
//        System.out.println(order_table);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblServiceCategory = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDrink = new javax.swing.JButton();
        btnMainFood = new javax.swing.JButton();
        btnDesssert = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblServiceCategory.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblServiceCategory.setText("None");
        add(lblServiceCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Service Category :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        btnDrink.setBackground(new java.awt.Color(102, 0, 102));
        btnDrink.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnDrink.setForeground(new java.awt.Color(255, 255, 255));
        btnDrink.setText("Drink");
        btnDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinkActionPerformed(evt);
            }
        });
        add(btnDrink, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 20, 120, 60));

        btnMainFood.setBackground(new java.awt.Color(0, 153, 153));
        btnMainFood.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnMainFood.setForeground(new java.awt.Color(255, 255, 255));
        btnMainFood.setText("MainFood");
        btnMainFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainFoodActionPerformed(evt);
            }
        });
        add(btnMainFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 120, 60));

        btnDesssert.setBackground(new java.awt.Color(102, 102, 0));
        btnDesssert.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnDesssert.setForeground(new java.awt.Color(255, 255, 255));
        btnDesssert.setText("Dessert");
        btnDesssert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesssertActionPerformed(evt);
            }
        });
        add(btnDesssert, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 120, 60));

        jPanel1.setBorder(null);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1150, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMainFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainFoodActionPerformed
        jPanel1.removeAll();
        lblServiceCategory.setText(btnMainFood.getText());
        getUC(lblServiceCategory.getText());
    }//GEN-LAST:event_btnMainFoodActionPerformed

    private void btnDesssertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesssertActionPerformed
        jPanel1.removeAll();
        lblServiceCategory.setText(btnDesssert.getText());
        getUC(lblServiceCategory.getText());
        jPanel1.updateUI();
    }//GEN-LAST:event_btnDesssertActionPerformed

    private void btnDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinkActionPerformed
        jPanel1.removeAll();
        lblServiceCategory.setText(btnDrink.getText());
        getUC(lblServiceCategory.getText());
    }//GEN-LAST:event_btnDrinkActionPerformed
    
    private ucService uc;
    private ForComponent.SubJTable order_table;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesssert;
    private javax.swing.JButton btnDrink;
    private javax.swing.JButton btnMainFood;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblServiceCategory;
    // End of variables declaration//GEN-END:variables

    private void getUC(String serviceCat)
    {        
        int x = 5, y = 5;
        int col = 5;
        int col_increment = 0;
        
        try
        {
            String sql = "select name, image, price from tblService inner join tblservicecategory on tblservice.servicecategoryid = "
                    + "tblservicecategory.id where tblservicecategory.categoryname = '" + serviceCat + "'";
            
            Statement s = DataConnection.getDataCon().createStatement();
            ResultSet r = s.executeQuery(sql);
            
            while(r.next())
            {
                uc = new ucService(r.getString(1) + "", r.getString(2) + "", r.getString(3) + "",getOrder_table());
                //add(uc, new AbsoluteConstraints(x, y, 180, 260));
                jPanel1.add(uc, new AbsoluteConstraints(x, y, 180, 260));
                
                if(col_increment >= col)
                {
                    x = 5;
                    y += 260;
                    
                    col_increment = 0;
                }
                else if(col_increment < col)
                {
                    x += 185;
                    
                    col_increment++;
                }
            }
            
            r.close();
        } 
        catch (SQLException e) 
        {
            System.out.println(e.getMessage());
        }
    }
}