/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ForPanel;

import ForClass.DataConnection;
import ForUserControl.ucService;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author Tang Seakmeng
 */
public class UC_Generator extends javax.swing.JPanel {
    /**
     * Creates new form UC_Generator
     */
    
    private ucService uc;
    
    public UC_Generator() {
        initComponents();
//        getUC("MainFood");
    }
    
    public void getUC(String serviceCat)
    {    
//        this.removeAll();
//        
//        int x = 5, y = 5;
//        int col = 5;
//        int col_increment = 0;
//        
//        System.out.println("Service Category : " + serviceCat);
//        
//        try
//        {
//            String sql = "select name, image, price from tblService inner join tblservicecategory on tblservice.servicecategoryid = "
//                    + "tblservicecategory.id where tblservicecategory.categoryname = '" + serviceCat + "'";
//            
//            Statement s = DataConnection.getDataCon().createStatement();
//            ResultSet r = s.executeQuery(sql);
//            
//            while(r.next())
//            {                
//                uc = new ucService(r.getString(1) + "", r.getString(2) + "", r.getString(3) + "");
//                this.add(uc, new AbsoluteConstraints(x, y, 190, 260));
//                
//                if(col_increment >= col)
//                {
//                    x = 5;
//                    y += 260;
//                    
//                    col_increment = 0;
//                }
//                else if(col_increment < col)
//                {
//                    x += 185;
//                    
//                    col_increment++;
//                }
//            }
//            
//            r.close();
//        } 
//        catch (SQLException e) 
//        {
//            System.out.println("SQL Exception : " + e.getMessage());
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
