/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ForJFrame;

import ForComponent.JPictureBox;
import ForPanel.Booking_Details;
import ForPanel.Product_Managment;
import ForPanel.Staff_Management;
import ForPanel.Booking_Transaction;
import ForPanel.CheckIn_Details;
import ForPanel.Expense_Details;
import ForPanel.Expense_Transaction;
import ForPanel.Invoice_Details;
import ForPanel.User_Management;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import ForClass.CenterScreenJFrame;
import ForPanel.CheckIn_Transaction;
import ForPanel.Import_Details;
import ForPanel.Import_Transaction;
import ForPanel.Order_Details;
import ForPanel.Order_Transaction;
import ForPanel.Service_Management;
import ForPanel.Table_Checking;
import java.awt.FlowLayout;

/**
 *
 * @author Tang Seakmeng
 */

public class Main_Form extends javax.swing.JFrame implements Runnable{
    /**
     * Creates new form Main_Form
     */
    
    Thread th;
    
    int hours, minutes, seconds;
    String dd, mmmm, yyyy;  
    String timeStr, yearStr;
    
    public Main_Form() {
        th = new Thread(this);
        th.start();
        
        initComponents();
        
        lbUserAccount.setText(Log_In_Form.getGlobal_username());
        
        lblPanelName1.setText("Main Form");
    }
    
    public void DashBoardPicture()
    {
        ImageIcon im = new ImageIcon("././Image/Dashboard.png");
        
        JPictureBox jp = new JPictureBox();
        jp.setLayout(new FlowLayout());
        jp.setSize(1796, 785);
        jp.setLocation(0, 0);
        jp.setIcon(im);
        jp.setVisible(true);
//        this.getContentPane().add(jp);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem10 = new javax.swing.JMenuItem();
        btnLogOut = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbDate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnExit = new javax.swing.JToggleButton();
        pnMain = new javax.swing.JPanel();
        jPictureBox1 = new ForComponent.JPictureBox();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblPanelName = new javax.swing.JLabel();
        lblPanelName1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbUserAccount = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        muUserManagement = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        muProductManagement = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        muImport = new javax.swing.JMenuItem();
        muImportRecord = new javax.swing.JMenuItem();
        muServiceManagement = new javax.swing.JMenu();
        muServiceMangement = new javax.swing.JMenuItem();
        muOrderService = new javax.swing.JMenuItem();
        muOrderDetails = new javax.swing.JMenuItem();
        muInvoice = new javax.swing.JMenu();
        muInvoiceRecord = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        muExpenseTransaction = new javax.swing.JMenuItem();
        muExpenseRecord = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        muTableBooking = new javax.swing.JMenuItem();
        muTableBookingDetails = new javax.swing.JMenuItem();
        muTableCheckInTransaction = new javax.swing.JMenuItem();
        muCheckInDetails = new javax.swing.JMenuItem();
        muTableChecking = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();

        jMenuItem10.setText("jMenuItem10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 204));
        setMinimumSize(new java.awt.Dimension(1900, 1020));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        btnLogOut.setBackground(new java.awt.Color(102, 102, 0));
        btnLogOut.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogOut);
        btnLogOut.setBounds(1750, 890, 113, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Time :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 890, 39, 17);

        lbTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTime.setText("None");
        getContentPane().add(lbTime);
        lbTime.setBounds(80, 890, 230, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Date :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 920, 38, 17);

        lbDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbDate.setText("None");
        getContentPane().add(lbDate);
        lbDate.setBounds(80, 920, 260, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 102));
        jLabel3.setText("User Account :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1390, 30, 140, 22);

        btnExit.setBackground(new java.awt.Color(0, 153, 153));
        btnExit.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(1640, 890, 99, 60);

        pnMain.setBackground(new java.awt.Color(153, 153, 153));

        jPictureBox1.setBackground(new java.awt.Color(204, 204, 204));
        jPictureBox1.setImageMode(ForComponent.JPictureBox.mode.Zoom);

        javax.swing.GroupLayout jPictureBox1Layout = new javax.swing.GroupLayout(jPictureBox1);
        jPictureBox1.setLayout(jPictureBox1Layout);
        jPictureBox1Layout.setHorizontalGroup(
            jPictureBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1828, Short.MAX_VALUE)
        );
        jPictureBox1Layout.setVerticalGroup(
            jPictureBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPictureBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPictureBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pnMain);
        pnMain.setBounds(30, 80, 1830, 800);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ForIcon/settings_48px.png"))); // NOI18N
        getContentPane().add(jButton1);
        jButton1.setBounds(1790, 10, 70, 60);

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("Multi-Tasking :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 29, 103, 19);

        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(139, 26, 160, 26);

        lblPanelName.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        lblPanelName.setForeground(new java.awt.Color(255, 51, 102));
        lblPanelName.setText("|");
        getContentPane().add(lblPanelName);
        lblPanelName.setBounds(1370, 10, 10, 50);

        lblPanelName1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lblPanelName1.setForeground(new java.awt.Color(255, 51, 102));
        lblPanelName1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPanelName1.setText("Panel Name");
        getContentPane().add(lblPanelName1);
        lblPanelName1.setBounds(1030, 20, 330, 47);

        jPanel1.setBackground(new java.awt.Color(255, 51, 102));

        lbUserAccount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbUserAccount.setForeground(new java.awt.Color(255, 255, 255));
        lbUserAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUserAccount.setText("None");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUserAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbUserAccount)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(1540, 20, 240, 50);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Staff");

        muUserManagement.setText("User Management");
        muUserManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muUserManagementActionPerformed(evt);
            }
        });
        jMenu3.add(muUserManagement);

        jMenuItem1.setText("Staff Managment");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        muProductManagement.setText("Inventory");

        jMenuItem2.setText("Inventory");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        muProductManagement.add(jMenuItem2);

        muImport.setText("Import Product");
        muImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muImportActionPerformed(evt);
            }
        });
        muProductManagement.add(muImport);

        muImportRecord.setText("Import Record");
        muImportRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muImportRecordActionPerformed(evt);
            }
        });
        muProductManagement.add(muImportRecord);

        jMenuBar1.add(muProductManagement);

        muServiceManagement.setText("Service");

        muServiceMangement.setText("Service");
        muServiceMangement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muServiceMangementActionPerformed(evt);
            }
        });
        muServiceManagement.add(muServiceMangement);

        muOrderService.setText("Order Transaction");
        muOrderService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muOrderServiceActionPerformed(evt);
            }
        });
        muServiceManagement.add(muOrderService);

        muOrderDetails.setText("Order Details");
        muOrderDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muOrderDetailsActionPerformed(evt);
            }
        });
        muServiceManagement.add(muOrderDetails);

        jMenuBar1.add(muServiceManagement);

        muInvoice.setText("Invoice");

        muInvoiceRecord.setText("Invoice Record");
        muInvoiceRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muInvoiceRecordActionPerformed(evt);
            }
        });
        muInvoice.add(muInvoiceRecord);

        jMenuBar1.add(muInvoice);

        jMenu4.setText("Expense");

        muExpenseTransaction.setText("Expense Transaction");
        muExpenseTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muExpenseTransactionActionPerformed(evt);
            }
        });
        jMenu4.add(muExpenseTransaction);

        muExpenseRecord.setText("Expense Record");
        muExpenseRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muExpenseRecordActionPerformed(evt);
            }
        });
        jMenu4.add(muExpenseRecord);

        jMenuBar1.add(jMenu4);

        jMenu7.setText("Table");

        muTableBooking.setText("Booking Transaction");
        muTableBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muTableBookingActionPerformed(evt);
            }
        });
        jMenu7.add(muTableBooking);

        muTableBookingDetails.setText("Booking Details");
        muTableBookingDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muTableBookingDetailsActionPerformed(evt);
            }
        });
        jMenu7.add(muTableBookingDetails);

        muTableCheckInTransaction.setText("Check In Transaction");
        muTableCheckInTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muTableCheckInTransactionActionPerformed(evt);
            }
        });
        jMenu7.add(muTableCheckInTransaction);

        muCheckInDetails.setText("Check In Details");
        muCheckInDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muCheckInDetailsActionPerformed(evt);
            }
        });
        jMenu7.add(muCheckInDetails);

        muTableChecking.setText("Check for Available");
        muTableChecking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muTableCheckingActionPerformed(evt);
            }
        });
        jMenu7.add(muTableChecking);

        jMenuBar1.add(jMenu7);

        jMenu6.setText("About");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    JPictureBox pb;
    
    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
//        th.interrupt();
        this.dispose();
        
        Log_In_Form log_In = new Log_In_Form();
        log_In.setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void muUserManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muUserManagementActionPerformed
        lblPanelName1.setText("User Management");
        
        User_Management um = new User_Management();
        AddJPanelFormToJPanel(um);
    }//GEN-LAST:event_muUserManagementActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        CenterScreenJFrame.CenteredFrame(this);
        //DashBoardPicture();
        
        ImageIcon im = new ImageIcon("././Image/Dashboard.png");
        jPictureBox1.setIcon(im);
        pb = jPictureBox1;
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        lblPanelName1.setText("Inventory Management");
        
        Product_Managment um = new Product_Managment();
        AddJPanelFormToJPanel(um);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        lblPanelName1.setText("Staff Management");
        
        Staff_Management um = new Staff_Management();
        AddJPanelFormToJPanel(um);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void muTableBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muTableBookingActionPerformed
        lblPanelName1.setText("Table Booking Transaction");
        
        Booking_Transaction tb = new Booking_Transaction();
        AddJPanelFormToJPanel(tb);
    }//GEN-LAST:event_muTableBookingActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        lblPanelName1.setText("Main Form");
        
        pnMain.removeAll();
        pnMain.setLayout(new java.awt.BorderLayout());
        pnMain.setVisible(true);
        pnMain.add(jPictureBox1);

        ImageIcon im = new ImageIcon("././Image/Dashboard.png");
        jPictureBox1.setIcon(im);
        pb = jPictureBox1;
    }//GEN-LAST:event_btnExitActionPerformed

    private void muTableBookingDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muTableBookingDetailsActionPerformed
        lblPanelName1.setText("Table Booking History");
        
        Booking_Details bd = new Booking_Details();
        AddJPanelFormToJPanel(bd);
    }//GEN-LAST:event_muTableBookingDetailsActionPerformed

    private void muTableCheckInTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muTableCheckInTransactionActionPerformed
        lblPanelName1.setText("Table Check In Transaction");
        
        CheckIn_Transaction ct = new CheckIn_Transaction();
        AddJPanelFormToJPanel(ct);
    }//GEN-LAST:event_muTableCheckInTransactionActionPerformed

    private void muExpenseTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muExpenseTransactionActionPerformed
        lblPanelName1.setText("Expense Transaction");
        
        Expense_Transaction bd = new Expense_Transaction();
        AddJPanelFormToJPanel(bd);
    }//GEN-LAST:event_muExpenseTransactionActionPerformed

    private void muExpenseRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muExpenseRecordActionPerformed
        lblPanelName1.setText("Expense History");
        
        Expense_Details bd = new Expense_Details();
        AddJPanelFormToJPanel(bd);
    }//GEN-LAST:event_muExpenseRecordActionPerformed

    private void muInvoiceRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muInvoiceRecordActionPerformed
        lblPanelName1.setText("Invoice History");
        
        Invoice_Details bd = new Invoice_Details();
        AddJPanelFormToJPanel(bd);
    }//GEN-LAST:event_muInvoiceRecordActionPerformed

    private void muServiceMangementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muServiceMangementActionPerformed
        lblPanelName1.setText("Service Management");
        
        Service_Management sm = new Service_Management();
        AddJPanelFormToJPanel(sm);
    }//GEN-LAST:event_muServiceMangementActionPerformed

    private void muOrderServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muOrderServiceActionPerformed
        lblPanelName1.setText("Order Service Management");
        
        Order_Transaction ot = new Order_Transaction();
        AddJPanelFormToJPanel(ot);
    }//GEN-LAST:event_muOrderServiceActionPerformed

    private void muTableCheckingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muTableCheckingActionPerformed
        lblPanelName1.setText("Table Check Transaction");
        
        Table_Checking tc = new Table_Checking();
        AddJPanelFormToJPanel(tc);
    }//GEN-LAST:event_muTableCheckingActionPerformed

    private void muImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muImportActionPerformed
        lblPanelName1.setText("Import Transaction");
        
        Import_Transaction it = new Import_Transaction();
        AddJPanelFormToJPanel(it);
    }//GEN-LAST:event_muImportActionPerformed

    private void muImportRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muImportRecordActionPerformed
        lblPanelName1.setText("Import History");
        
        Import_Details id = new Import_Details();
        AddJPanelFormToJPanel(id);
    }//GEN-LAST:event_muImportRecordActionPerformed

    private void muOrderDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muOrderDetailsActionPerformed
        lblPanelName1.setText("Order History");
        
        Order_Details od = new Order_Details();
        AddJPanelFormToJPanel(od);
    }//GEN-LAST:event_muOrderDetailsActionPerformed

    private void muCheckInDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muCheckInDetailsActionPerformed
        lblPanelName1.setText("Check In History");
        
        CheckIn_Details cd = new CheckIn_Details();
        AddJPanelFormToJPanel(cd);
    }//GEN-LAST:event_muCheckInDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Form().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnExit;
    private javax.swing.JToggleButton btnLogOut;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    public ForComponent.JPictureBox jPictureBox1;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbTime;
    private javax.swing.JLabel lbUserAccount;
    private javax.swing.JLabel lblPanelName;
    private javax.swing.JLabel lblPanelName1;
    private javax.swing.JMenuItem muCheckInDetails;
    private javax.swing.JMenuItem muExpenseRecord;
    private javax.swing.JMenuItem muExpenseTransaction;
    private javax.swing.JMenuItem muImport;
    private javax.swing.JMenuItem muImportRecord;
    private javax.swing.JMenu muInvoice;
    private javax.swing.JMenuItem muInvoiceRecord;
    private javax.swing.JMenuItem muOrderDetails;
    private javax.swing.JMenuItem muOrderService;
    private javax.swing.JMenu muProductManagement;
    private javax.swing.JMenu muServiceManagement;
    private javax.swing.JMenuItem muServiceMangement;
    private javax.swing.JMenuItem muTableBooking;
    private javax.swing.JMenuItem muTableBookingDetails;
    private javax.swing.JMenuItem muTableCheckInTransaction;
    private javax.swing.JMenuItem muTableChecking;
    private javax.swing.JMenuItem muUserManagement;
    public javax.swing.JPanel pnMain;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(true)
        {
            try {
                Calendar c = Calendar.getInstance();
                
                hours = c.get(Calendar.HOUR);
                minutes = c.get(Calendar.MINUTE);
                seconds = c.get(Calendar.SECOND);
                dd = c.get(Calendar.DAY_OF_MONTH) + "";
                mmmm = c.get(Calendar.MONTH) + "";
                yyyy = c.get(Calendar.YEAR) + "";
                
                SimpleDateFormat sdf = new SimpleDateFormat("hh : mm : ss a");
                SimpleDateFormat sdf2 = new SimpleDateFormat("EEE : dd / MM / yyyy");;
                
                Date date = c.getTime();
                
                timeStr = sdf.format(date);
                yearStr = sdf2.format(date);
                
                lbTime.setText(timeStr);
                lbDate.setText(yearStr);
            } catch (Exception ex) {
//                JOptionPane.showMessageDialog(this, "Error : " + ex.getMessage());
            }
        }
    }
    
    public void AddJPanelFormToJPanel(JPanel jp)
    {
        pnMain.removeAll();
        jp.setVisible(true);
        pnMain.setLayout(new java.awt.BorderLayout());
        pnMain.add(jp);
    }
}
