/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ForDialog;

import ForClass.DataConnection;
import ForClass.DefaultLogo;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Tang Seakmeng
 */
public class Import_History_Details extends javax.swing.JDialog {

    /**
     * Creates new form Import_History_Details
     */
    public Import_History_Details(java.awt.Frame parent, boolean modal, String[] arr) {
        super(parent, modal);
        initComponents();
        
        ImageIcon im = new ImageIcon(DefaultLogo.imagePath);
        pictureBoxLogo.setIcon(im);
        
        lbImportID.setText(arr[0]);
        lbImportDate.setText(arr[1]);
        lbImportSubtotal.setText(arr[2]);
        lbInvoiceId.setText(arr[3]);
        lbSupplierName.setText(arr[4]);
        lbStaffName.setText(arr[5]);
        
        try
        {
            String sql = "select p.barcode, p.name, c.CategoryName, im.Quantity, im.CostOfSale,  round((im.Quantity * im.CostOfSale),2) as Subtotal\n" +
                            "from tblimportdetails im\n" +
                            "inner join tblproduct p\n" +
                            "on im.productid = p.id\n" +
                            "inner join tblcategory c\n" +
                            "on c.id = p.categoryid where importid = " + arr[0] + ";"; 
            
            Statement s = DataConnection.getDataCon().createStatement();
            ResultSet r = s.executeQuery(sql);
            
            while(r.next())
            {
                subJTable1.addRow(r.getString(1), r.getString(2), r.getString(3), r.getString(4), r.getString(5), r.getString(6));
            }
            
            r.close();
        } 
        catch (SQLException e) 
        {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        pictureBoxLogo = new ForComponent.JPictureBox();
        lbImportID = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbImportDate = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbImportSubtotal = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbInvoiceId = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbSupplierName = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbStaffName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        subJTable1 = new ForComponent.SubJTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel8.setText("Import ID          :");

        pictureBoxLogo.setImageMode(ForComponent.JPictureBox.mode.Zoom);

        javax.swing.GroupLayout pictureBoxLogoLayout = new javax.swing.GroupLayout(pictureBoxLogo);
        pictureBoxLogo.setLayout(pictureBoxLogoLayout);
        pictureBoxLogoLayout.setHorizontalGroup(
            pictureBoxLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );
        pictureBoxLogoLayout.setVerticalGroup(
            pictureBoxLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        lbImportID.setBackground(new java.awt.Color(0, 0, 0));
        lbImportID.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lbImportID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImportID.setText("00000001");

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel10.setText("Import Date      :");

        lbImportDate.setBackground(new java.awt.Color(0, 0, 0));
        lbImportDate.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lbImportDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImportDate.setText("00000001");

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel12.setText("Import Subtotal :");

        lbImportSubtotal.setBackground(new java.awt.Color(0, 0, 0));
        lbImportSubtotal.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lbImportSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImportSubtotal.setText("00000001");

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel14.setText("Invoice ID        :");

        lbInvoiceId.setBackground(new java.awt.Color(0, 0, 0));
        lbInvoiceId.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lbInvoiceId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInvoiceId.setText("00000001");

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel16.setText("Supplier Name :");

        lbSupplierName.setBackground(new java.awt.Color(0, 0, 0));
        lbSupplierName.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lbSupplierName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSupplierName.setText("00000001");

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel18.setText("Staff Name      :");

        lbStaffName.setBackground(new java.awt.Color(0, 0, 0));
        lbStaffName.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lbStaffName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStaffName.setText("00000001");

        subJTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Barcode", "Product Name", "Category Name", "Quantity", "Cost Of Sale", "Subtotal"
            }
        ));
        subJTable1.setRowHeight(30);
        jScrollPane2.setViewportView(subJTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 29, Short.MAX_VALUE)
                        .addComponent(pictureBoxLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbImportDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(lbImportID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbImportSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16))
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbInvoiceId, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pictureBoxLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lbInvoiceId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(lbSupplierName))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(lbStaffName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lbImportID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lbImportDate))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lbImportSubtotal))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Import_History_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Import_History_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Import_History_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Import_History_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Import_History_Details dialog = new Import_History_Details(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbImportDate;
    private javax.swing.JLabel lbImportID;
    private javax.swing.JLabel lbImportSubtotal;
    private javax.swing.JLabel lbInvoiceId;
    private javax.swing.JLabel lbStaffName;
    private javax.swing.JLabel lbSupplierName;
    private ForComponent.JPictureBox pictureBoxLogo;
    private ForComponent.SubJTable subJTable1;
    // End of variables declaration//GEN-END:variables
}
