/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test_Injection;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tang Seakmeng
 */
public class NewJPanel2 extends javax.swing.JPanel {

    /**
     * @return the table
     */
    public JTable getTable() {
        return table;
    }

    /**
     * @param table the table to set
     */
    public void setTable(JTable table) {
        this.table = table;
    }

    /**
     * @return the btn
     */
    public javax.swing.JButton getBtn() {
        return btn;
    }

    /**
     * @param btn the btn to set
     */
    public void setBtn(javax.swing.JButton btn) {
        this.btn = btn;
    }

    /**
     * Creates new form NewJPanel2
     */
    public NewJPanel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newJPanel1 = new Test_Injection.NewJPanel();
        newJPanel11 = new Test_Injection.NewJPanel1();
        btn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(newJPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));
        add(newJPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 296, -1, -1));

        btn.setText("jButton1");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        add(btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    
    private JTable table;
    
    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        JOptionPane.showMessageDialog(this, "Hi");
        
        DefaultTableModel mod=(DefaultTableModel)table.getModel();
        mod.addRow(new String[]{"00","vuth"});
        
        System.out.println(mod.getColumnCount());
        System.out.println(mod.getRowCount());
    }//GEN-LAST:event_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private Test_Injection.NewJPanel newJPanel1;
    private Test_Injection.NewJPanel1 newJPanel11;
    // End of variables declaration//GEN-END:variables
}
